[2025-03-21T20:10:49.313+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/app.py
[2025-03-21T20:10:49.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:10:49.318+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:10:49.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:10:49.655+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:10:49.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:10:49.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:10:50.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.707 seconds
[2025-03-21T20:11:20.130+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/app.py
[2025-03-21T20:11:20.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:11:20.139+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:11:20.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:11:20.443+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:11:20.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:11:20.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:11:20.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.357 seconds
[2025-03-21T20:14:04.926+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/app.py
[2025-03-21T20:14:04.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:14:04.931+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:14:04.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:14:05.168+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:14:05.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:14:05.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:14:05.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.283 seconds
[2025-03-21T20:14:35.398+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/app.py
[2025-03-21T20:14:35.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:14:35.415+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:14:35.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:14:35.670+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:14:35.664+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:14:35.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:14:35.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.333 seconds
[2025-03-21T20:15:05.925+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/app.py
[2025-03-21T20:15:05.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:15:05.930+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:15:05.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:15:06.134+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:15:06.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:15:06.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:15:06.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.246 seconds
[2025-03-21T20:15:36.394+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/app.py
[2025-03-21T20:15:36.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:15:36.398+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:15:36.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:15:36.538+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:15:36.533+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:15:36.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:15:36.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.171 seconds
[2025-03-21T20:16:07.071+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/app.py
[2025-03-21T20:16:07.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:16:07.075+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:16:07.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:16:07.262+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:16:07.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:16:07.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:16:07.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.227 seconds
[2025-03-21T20:16:37.542+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/app.py
[2025-03-21T20:16:37.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:16:37.546+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:16:37.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:16:37.742+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:16:37.736+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:16:37.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:16:37.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.233 seconds
[2025-03-21T20:24:02.832+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/app.py
[2025-03-21T20:24:02.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:24:02.838+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:24:02.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:24:03.115+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:24:03.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:24:03.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:24:03.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.331 seconds
[2025-03-21T20:24:33.383+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/app.py
[2025-03-21T20:24:33.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:24:33.387+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:24:33.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:24:33.584+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:24:33.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:24:33.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:24:33.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.232 seconds
[2025-03-21T20:25:03.907+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/app.py
[2025-03-21T20:25:03.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:25:03.915+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:25:03.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:25:04.134+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:25:04.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:25:04.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:25:04.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.273 seconds
[2025-03-21T20:25:34.766+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/app.py
[2025-03-21T20:25:34.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:25:34.769+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:25:34.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:25:34.924+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:25:34.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:25:34.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:25:34.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.188 seconds
[2025-03-21T20:26:05.357+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/app.py
[2025-03-21T20:26:05.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:26:05.361+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:26:05.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:26:05.509+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:26:05.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:26:05.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:26:05.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.179 seconds
[2025-03-21T20:26:35.712+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/app.py
[2025-03-21T20:26:35.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:26:35.716+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:26:35.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:26:35.897+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:26:35.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:26:35.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:26:35.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.219 seconds
[2025-03-21T20:27:06.353+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/app.py
[2025-03-21T20:27:06.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:27:06.356+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:27:06.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:27:06.517+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:27:06.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:27:06.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:27:06.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.193 seconds
[2025-03-21T20:27:37.008+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/app.py
[2025-03-21T20:27:37.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:27:37.012+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:27:37.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:27:37.247+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:27:37.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:27:37.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:27:37.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.274 seconds
[2025-03-21T20:28:07.705+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/app.py
[2025-03-21T20:28:07.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:28:07.709+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:28:07.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:28:07.864+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:28:07.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:28:07.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:28:07.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.185 seconds
[2025-03-21T20:28:38.098+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/app.py
[2025-03-21T20:28:38.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:28:38.101+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:28:38.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:28:38.265+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:28:38.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:28:38.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:28:38.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.197 seconds
[2025-03-21T20:29:08.814+0000] {processor.py:186} INFO - Started process (PID=702) to work on /opt/airflow/dags/app.py
[2025-03-21T20:29:08.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:29:08.819+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:29:08.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:29:09.059+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:29:09.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:29:09.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:29:09.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.280 seconds
[2025-03-21T20:29:39.141+0000] {processor.py:186} INFO - Started process (PID=766) to work on /opt/airflow/dags/app.py
[2025-03-21T20:29:39.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:29:39.145+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:29:39.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:29:39.351+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:29:39.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:29:39.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:29:39.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.252 seconds
[2025-03-21T20:30:09.530+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/app.py
[2025-03-21T20:30:09.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:30:09.535+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:30:09.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:30:09.719+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:30:09.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:30:09.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:30:09.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.222 seconds
[2025-03-21T20:30:39.874+0000] {processor.py:186} INFO - Started process (PID=895) to work on /opt/airflow/dags/app.py
[2025-03-21T20:30:39.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:30:39.877+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:30:39.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:30:40.057+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:30:40.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:30:40.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:30:40.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.210 seconds
[2025-03-21T20:31:10.156+0000] {processor.py:186} INFO - Started process (PID=960) to work on /opt/airflow/dags/app.py
[2025-03-21T20:31:10.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:31:10.159+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:31:10.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:31:10.315+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:31:10.309+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:31:10.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:31:10.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.185 seconds
[2025-03-21T20:31:40.662+0000] {processor.py:186} INFO - Started process (PID=1025) to work on /opt/airflow/dags/app.py
[2025-03-21T20:31:40.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:31:40.668+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:31:40.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:31:40.862+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:31:40.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:31:40.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:31:40.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.246 seconds
[2025-03-21T20:32:11.703+0000] {processor.py:186} INFO - Started process (PID=1089) to work on /opt/airflow/dags/app.py
[2025-03-21T20:32:11.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:32:11.706+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:32:11.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:32:11.852+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:32:11.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:32:11.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:32:11.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.178 seconds
[2025-03-21T20:32:42.003+0000] {processor.py:186} INFO - Started process (PID=1153) to work on /opt/airflow/dags/app.py
[2025-03-21T20:32:42.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:32:42.007+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:32:42.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:32:42.158+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:32:42.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:32:42.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:32:42.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.180 seconds
[2025-03-21T20:33:12.473+0000] {processor.py:186} INFO - Started process (PID=1217) to work on /opt/airflow/dags/app.py
[2025-03-21T20:33:12.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:33:12.477+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:33:12.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:33:12.646+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:33:12.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:33:12.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:33:12.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.202 seconds
[2025-03-21T20:33:21.826+0000] {processor.py:186} INFO - Started process (PID=1220) to work on /opt/airflow/dags/app.py
[2025-03-21T20:33:21.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-03-21T20:33:21.830+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:33:21.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-03-21T20:33:22.078+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:33:22.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 14, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-21T20:33:22.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-03-21T20:33:22.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.293 seconds
